### ISSUE TITLE
Bad link to `add it`

### ISSUE THREAD

**Issue by johannchopin** [clean-css/clean-css.github.io#13]
@jakubpawlowicz  At the bottom of the website there is this paragraph:

> CSS optimizing happens directly in your browser using a browser-compatible build of clean-css. If you miss any functionality, you are more than welcome to [add it](https://github.com/clean-css/clean-css.github.io)!

The link to `add it` currently redirects to the website repo but I guess that it should be the issues of clean-css: https://github.com/clean-css/clean-css/issues.

Is it an error?

**Comment by jakubpawlowicz** [comment]
Hey @johannchopin - it was easier when we had one repo!

Let's point people to clean-css issues tracker.

**Comment by johannchopin** [comment]
@jakubpawlowicz Fixed in [f4ffd99](https://github.com/clean-css/clean-css.github.io/commit/f4ffd99bdc6b249b5e0abc6684ebdfe28c41a95e) 👍

**Comment by jakubpawlowicz** [comment]
:+1:
