### ISSUE TITLE
Website version

### ISSUE THREAD

**Issue by jakubpawlowicz** [clean-css/clean-css.github.io#2]
Hey @johannchopin - should we bump `package.json` version when I update clean-css dependency minor version? No idea what would you prefer.

**Comment by johannchopin** [comment]
Hey 👋 I guess it's more clear to bump it so you don't need to check the `yarn.lock` file in case you want to be sure.

**Comment by jakubpawlowicz** [comment]
:+1: one more question - should I bump it to 1.0.1 when bumping clean-css to 5.1.4?

**Comment by johannchopin** [comment]
Yes that will be more clean so I guess we also need to add a CHANGELOG file. I really like the [keep a changelog](https://keepachangelog.com/en/1.0.0/) convention to maintain history. Would it be ok for you to use that?

**Comment by jakubpawlowicz** [comment]
:+1: for changelog

**Comment by johannchopin** [comment]
So I created the [CHANGELOG.md](https://github.com/clean-css/clean-css.github.io/blob/main/CHANGELOG.md) file 👍  If you don't have other questions feel free to close this one 😄

**Comment by jakubpawlowicz** [comment]
Nah, that's it, thanks!
